// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MvcCamp.Models;
using System;

namespace MvcCamp.Migrations
{
    [DbContext(typeof(MvcCampContext))]
    [Migration("20171023161629_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("MvcCamp.Models.Camp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BeltGrade");

                    b.Property<DateTime>("DateRegistered");

                    b.Property<decimal>("DepositPutDown");

                    b.Property<string>("FullName");

                    b.HasKey("ID");

                    b.ToTable("Camp");
                });
#pragma warning restore 612, 618
        }
    }
}
